### ISSUE TITLE
Trust store password is incorrect following a bosh restart

### ISSUE THREAD

**Issue by iferunsewe** [pivotal-cf/credhub-release#24] opened 2018-06-13 13:06 UTC
What version of the credhub server you are using?

1.9.3

What version of the credhub cli you are using?

N/A

If you were attempting to accomplish a task, what was it you were attempting to do?

Trying to do a `bosh restart` on a fresh deployment of concourse.

What did you expect to happen?

We expected the job to restart successfully

What was the actual behavior?

The job fails for credhub and the following output is produced.

```
Using environment '<environment>' as client 'admin'

Task 47

Task 47 | 09:51:25 | Preparing deployment: Preparing deployment (00:00:01)
Task 47 | 09:51:29 | Preparing package compilation: Finding packages to compile (00:00:01)
Task 47 | 09:51:30 | Updating instance web: web/3e75a779-5735-42b9-b025-5983eff2e72b (0) (canary) (00:12:03)
                   L Error: Action Failed get_task: Task 3f8ac090-4793-43f0-67a5-75d96aa80d80 result: 1 of 3 post-start scripts failed. Failed Jobs: credhub. Successful Jobs: uaa, grafana.
Task 47 | 10:03:33 | Error: Action Failed get_task: Task 3f8ac090-4793-43f0-67a5-75d96aa80d80 result: 1 of 3 post-start scripts failed. Failed Jobs: credhub. Successful Jobs: uaa, grafana.

Task 47 Started  Wed Jun 13 09:51:25 UTC 2018
Task 47 Finished Wed Jun 13 10:03:33 UTC 2018
Task 47 Duration 00:12:08
Task 47 error

Capturing task '47' output:
  Expected task '47' to succeed but state is 'error'

Exit code 1
```

After investigating further we found the following in the credhub.log
```
Caused by: java.io.IOException: Keystore was tampered with, or password was incorrect
        at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:780) ~[?:1.8.0_172]
        at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56) ~[?:1.8.0_172]
        at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224) ~[?:1.8.0_172]
        at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70) ~[?:1.8.0_172]
        at java.security.KeyStore.load(KeyStore.java:1445) ~[?:1.8.0_172]
        at sun.security.ssl.TrustManagerFactoryImpl.getCacertsKeyStore(TrustManagerFactoryImpl.java:226) ~[?:1.8.0_172]
        at sun.security.ssl.SSLContextImpl$DefaultManagersHolder.getTrustManagers(SSLContextImpl.java:771) ~[?:1.8.0_172]
        at sun.security.ssl.SSLContextImpl$DefaultManagersHolder.<clinit>(SSLContextImpl.java:748) ~[?:1.8.0_172]
        at sun.security.ssl.SSLContextImpl$DefaultSSLContext.<init>(SSLContextImpl.java:913) ~[?:1.8.0_172]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_172]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_172]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_172]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_172]
        at java.security.Provider$Service.newInstance(Provider.java:1595) ~[?:1.8.0_172]
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:236) ~[?:1.8.0_172]
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:164) ~[?:1.8.0_172]
        at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156) ~[?:1.8.0_172]
        at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96) ~[?:1.8.0_172]
        at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:122) ~[?:1.8.0_172]
        at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:44) ~[postgresql-42.2.1.jar!/:42.2.1]
        ... 48 more
Caused by: java.security.UnrecoverableKeyException: Password verification failed
        at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:778) ~[?:1.8.0_172]
        at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56) ~[?:1.8.0_172]
        at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224) ~[?:1.8.0_172]
        at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70) ~[?:1.8.0_172]
        at java.security.KeyStore.load(KeyStore.java:1445) ~[?:1.8.0_172]
        at sun.security.ssl.TrustManagerFactoryImpl.getCacertsKeyStore(TrustManagerFactoryImpl.java:226) ~[?:1.8.0_172]
        at sun.security.ssl.SSLContextImpl$DefaultManagersHolder.getTrustManagers(SSLContextImpl.java:771) ~[?:1.8.0_172]
        at sun.security.ssl.SSLContextImpl$DefaultManagersHolder.<clinit>(SSLContextImpl.java:748) ~[?:1.8.0_172]
        at sun.security.ssl.SSLContextImpl$DefaultSSLContext.<init>(SSLContextImpl.java:913) ~[?:1.8.0_172]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_172]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_172]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_172]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_172]
        at java.security.Provider$Service.newInstance(Provider.java:1595) ~[?:1.8.0_172]
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:236) ~[?:1.8.0_172]
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:164) ~[?:1.8.0_172]
        at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156) ~[?:1.8.0_172]
        at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96) ~[?:1.8.0_172]
        at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:122) ~[?:1.8.0_172]
        at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:44) ~[postgresql-42.2.1.jar!/:42.2.1]
        ... 48 more
2018-06-13T09:53:31.295Z [main] .... ERROR --- ConnectionPool: Unable to create initial connections of pool.
org.postgresql.util.PSQLException: SSL error: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
```
This suggested that the password was wrong for the trust store. We found that the password displayed in the `config/application.yml` did not match the one used to launch the server in the `ctl` script. 

```
web/3e75a779-5735-42b9-b025-5983eff2e72b:/var/vcap/jobs/credhub# cat config/application.yml | grep trust
  trust_store: /var/vcap/jobs/credhub/config/trust_store.jks
  trust_store_password: Mt5WbtjoSlgku0wioEpNrk5oxOZ47iZg
```
the trust_store_password does not match:
```
web/3e75a779-5735-42b9-b025-5983eff2e72b:/var/vcap/jobs/credhub# cat bin/ctl | grep trust
-Djdk.tls.namedGroups="secp384r1" \-Djavax.net.ssl.trustStore=/var/vcap/jobs/credhub/config/trust_store.jks \
  -Djavax.net.ssl.trustStorePassword=0olVqtPifTqfqmGPaHYRxFhBEE315deA \-ea -jar *.jar
```
After debugging further, we found that the `init_key_stores.sh` which is called by the `pre-start` script does not successfully substitute the generated trust store password for the `TRUST_STORE_PASSWORD_PLACEHOLDER`. If the pre start script has already run then no newly generated passwords will be substituted into these files as the placeholder will not be there.

We managed to get this working by manually replacing the old passwords with the placeholder before running `bosh restart` again.

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

If you are a PCF customer with an Operation Manager (PCF Ops Manager) please direct your questions to support (https://support.pivotal.io/)

**Comment by voelzmo** [comment] 2018-07-27 13:56
Just happened to hit this issue as well with CredHub 1.9.5. Symptoms are slightly different, even worse than described above:
* deploying bosh didn't fail, all jobs started successfully
* once we tried to deploy anything that tried to use CredHub, this fails very silently with `invalid token`

The `pre-start` script is not idempotent, although it contains a check that tries to achieve this: 
* configurator always writes a new `application.yml` with the placeholder `KEY_STORE_PASSWORD_PLACEHOLDER`: https://github.com/pivotal-cf/credhub-release/blob/master/jobs/credhub/templates/pre-start.erb#L8
* Check for 'is truststore already set up?' always returns 'false': https://github.com/pivotal-cf/credhub-release/blob/master/jobs/credhub/templates/pre-start.erb#L38-L39
* `init_key_stores.sh` deletes existing keystore and creates one with a new password
* if templates had not been re-rendered by the director (and therefore contain the placeholder `KEY_STORE_PASSWORD_PLACEHOLDER` instead of the previous password), `ctl` and `credhub` now contain the old password, while the keystore has a new password

suggested solution: make `pre-start` idempotent, as suggested by bosh documentation: https://bosh.io/docs/pre-start/

Unfortunately, this seems so happen quite often now, most notably on AWS. I'm not sure yet why this is the case right now, but this makes it pretty awful for us.

This bug has been open for about two weeks without any acknowledgement or reaction – is this something you would be able to prioritze?

**Comment by voelzmo** [comment] 2018-07-31 12:12
For reference: here is what we ended up doing for our fork for now. Just in case someone has the same problem and needs to fix this right now.
```
From 85bcfa210bd942e9c6c8c81d58cd4d0a2b9c37f8 Mon Sep 17 00:00:00 2001
Date: Mon, 30 Jul 2018 16:45:26 +0200
Subject: [PATCH] make pre-start idempotent
---
 jobs/credhub/templates/pre-start.erb | 6 ++----
 1 file changed, 2 insertions(+), 4 deletions(-)

diff --git a/jobs/credhub/templates/pre-start.erb b/jobs/credhub/templates/pre-start.erb
index aaf41ca..4dd970d 100644
--- a/jobs/credhub/templates/pre-start.erb
+++ b/jobs/credhub/templates/pre-start.erb
@@ -3,9 +3,6 @@
 <% using_hsm = p('credhub.encryption.providers').any? { |provider| provider['type'] == "hsm" } %>
 <% port = p('credhub.port') %>
 
-
-cat /var/vcap/jobs/credhub/config/config.json | /var/vcap/packages/configurator/bin/configurator/configurator > /var/vcap/jobs/credhub/config/application.yml
-
 <%
   begin
     p('credhub.tls.certificate')
@@ -36,10 +33,11 @@ export JAVA_HOME=/var/vcap/packages/openjdk_1.8.0/jre
 chown -R vcap /var/vcap/jobs/credhub/config
 chmod 600 /var/vcap/jobs/credhub/config/*
 
-if [ `grep KEY_STORE_PASSWORD_PLACEHOLDER /var/vcap/jobs/credhub/config/application.yml | wc -l` -eq 0 ]; then
+if [ `grep TRUST_STORE_PASSWORD_PLACEHOLDER /var/vcap/jobs/credhub/bin/ctl| wc -l` -eq 0 ]; then
   echo "Key store appears to be initialized. Skipping key store and cert initialization."
 else
   echo "Key store appears to be uninitialized. Setting up key store and installing certs."
+  cat /var/vcap/jobs/credhub/config/config.json | /var/vcap/packages/configurator/bin/configurator/configurator > /var/vcap/jobs/credhub/config/application.yml
   /var/vcap/jobs/credhub/bin/init_key_stores.sh
 fi
```

**Comment by voelzmo** [comment] 2018-07-31 18:29
Nope, no HSM being used. Would that change anything about the script being idempotent?

**Comment by dpb587-pivotal** [comment] 2018-07-31 21:58
Shouldn't; just thought it might be a factor in the AWS error-tendencies.

**Comment by ansd** [comment] 2018-08-02 11:29
Underlying issue why the credhub pre-start script got executed multiple times on AWS:
https://github.com/cloudfoundry/bosh/issues/2017

**Comment by mdelillo** [comment] 2018-08-02 18:57
@iferunsewe I think we fixed this issue [here](https://github.com/pivotal-cf/credhub-release/commit/f8eba9843bb4759fc0fca5e592eb05dfa14448ce) but never cut a 1.9.x release including it. It's in 2.0, but we'll also back-port in case you aren't ready to upgrade to that version yet.

@voelzmo We weren't able to reproduce your issue using 1.9.5, do you think the above commit would fix it? We were a little confused by the last step of your reproduction:

> if templates had not been re-rendered by the director (and therefore contain the placeholder KEY_STORE_PASSWORD_PLACEHOLDER instead of the previous password), ctl and credhub now contain the old password, while the keystore has a new password

What do you mean by the templates not being re-rendered? The `init_key_stores.sh` script is only ever called by the `pre-start` script, which ensures the placeholders are put into the `application.yml`. The check to see if the key store is initialized is unnecessary, but the script itself seems idempotent.

**Comment by voelzmo** [comment] 2018-08-02 20:10
`pre-start` is not idempotent, you should be able to easily test this with
* bosh deploy/create-env credhub
* ssh into the machine, see that passwords in `application.yml` and the `ctl` are the same
* `monit stop credhub`
* execute `/var/vcap/jobs/credhub/bin/pre-start`
* see that passwords in `application.yml` and the `ctl` are different
* check that the keystore password that works is the one from `application.yml`, as it gets re-generated

You can repeat this as often as you want, the keystore gets a new password on every execution of `pre-start`.

Above, I tried to explain why this is the case, and how the scenario of `pre-start` being executed twice happens. Sorry if this didn't come across quite right.

**Comment by mdelillo** [comment] 2018-08-08 21:55
@voelzmo The fix for this issue is in [1.9.6](https://github.com/pivotal-cf/credhub-release/releases/tag/1.9.6) and [2.0.1](https://github.com/pivotal-cf/credhub-release/releases/tag/2.0.1). The trust store password still gets changed in the pre-start, but we properly update it in all of the files.

**Comment by voelzmo** [comment] 2018-08-09 08:38
@mdelillo Thanks for letting me know! I'm a bit confused about the fix that you decided for, though. Could you help me understand why you decided to not make the script idempotent but change the way the replacement happens, such that there's no mismatch between the files containing the password?

**Comment by mdelillo** [comment] 2018-08-09 13:30
@voelzmo We change the password every time because it's the simplest thing for us to do and was the smallest change that fixed the issue. I suppose we could have generated the passwords once in another file and checked for the presence of that file to determine whether to regenerate them or not, but we didn't see much advantage to doing that over our solution. We would still want to recreate the trust stores every time the script is run, or at the very least add the certificates to the existing ones (in case the certs have changed).

**Closed** 2018-09-27 15:01 UTC
Labels: accepted
